version: '3'
services:
  postgres:
    env_file: "docker/.env.development"
    image: postgres:11.5-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PWD}"
    ports:
      - "5432:5432"
    expose:
      - "5432"
  redis:
    image: redis:6.0.5-alpine
    volumes:
      - ./tmp/redis:/var/lib/redis/data
    ports:
      - 6379:6379
  rails:
    env_file: "docker/.env.development"
    environment:
      POSTGRESQL_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PWD: 1234
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    volumes:
      - ./:/wanted_app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s
    command: /bin/bash -c docker/rails/docker-entrypoint.sh
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    image: wanted_rails